DROP TABLE IF EXISTS CLIENT CASCADE;
DROP TABLE IF EXISTS DEVICES CASCADE;
DROP TABLE IF EXISTS ALLERGENS CASCADE;
DROP TABLE IF EXISTS CLIENTS_TO_ALLERGIC CASCADE;
DROP TABLE IF EXISTS CLIENTS_TO_INTOLERANCE CASCADE;


CREATE TABLE CLIENT(
	appID VARCHAR(20) PRIMARY KEY NOT NULL,
	fbID VARCHAR(20) DEFAULT ''
);

CREATE TABLE DEVICES(
	ID VARCHAR(20) PRIMARY KEY NOT NULL,
	clientID VARCHAR(20),
	FOREIGN KEY (clientID) REFERENCES CLIENT(appID)
);

CREATE TABLE ALLERGENS(
	description VARCHAR(20) PRIMARY KEY NOT NULL
);

CREATE TABLE CLIENTS_TO_ALLERGIC(
	clientID VARCHAR(20),
	allergen VARCHAR(20),
	FOREIGN KEY(clientID) REFERENCES CLIENT(appID),
	FOREIGN KEY(allergen) REFERENCES ALLERGENS(description)
);

CREATE TABLE CLIENTS_TO_INTOLERANCE(
	clientID VARCHAR(20),
	allergen VARCHAR(20),
	FOREIGN KEY(clientID) REFERENCES CLIENT(appID),
	FOREIGN KEY(allergen) REFERENCES ALLERGENS(description)
);

INSERT INTO ALLERGENS(description) VALUES('LACTEOS');
INSERT INTO ALLERGENS(description) VALUES('GLUTEN');
INSERT INTO ALLERGENS(description) VALUES('AMENDOINS');
INSERT INTO ALLERGENS(description) VALUES('OVOS');
INSERT INTO ALLERGENS(description) VALUES('MARISCO');
INSERT INTO ALLERGENS(description) VALUES('MOLUSCOS');
INSERT INTO ALLERGENS(description) VALUES('MOSTARDA');
INSERT INTO ALLERGENS(description) VALUES('PEIXE');
INSERT INTO ALLERGENS(description) VALUES('SESAMO');
INSERT INTO ALLERGENS(description) VALUES('SOJA');
INSERT INTO ALLERGENS(description) VALUES('TREMOCOS');

